#!/bin/bash -eu

if [ "${BASH_SOURCE[0]}" != "$0" ]
then
  echo "${BASH_SOURCE[0]} must be executed, not sourced"
  return 1 # shouldn't use exit when sourced
fi

if [ "${FLOCKED:-}" != "$0" ]
then
  if FLOCKED="$0" flock -en -E 99 "$0" "$0" "$@" || case "$?" in
  99) echo already running
      exit 99
      ;;
  *)  exit $?
      ;;
  esac
  then
    # success
    exit 0
  fi
fi

HEADLESS_SETUP=${HEADLESS_SETUP:-false}
if [ "$HEADLESS_SETUP" = "false" ] && [ -t 0 ]
then
  # running in terminal in non-headless mode
  if [ -f /boot/teslausb_setup_variables.conf ] || [ -f /root/teslausb_setup_variables.conf ]
  then
    # headless setup variables are available
    read -r -p "Read setup info from teslausb_setup_variables.conf (yes/no/cancel)? " answer
    case ${answer:0:1} in
      y|Y )
          HEADLESS_SETUP=true
      ;;
      n|N )
      ;;
      * )
          exit
      ;;
    esac
  fi
fi

REPO=${REPO:-macpraveen}
BRANCH=${BRANCH:-main-dev}
USE_LED_FOR_SETUP_PROGRESS=true
CONFIGURE_ARCHIVING=${CONFIGURE_ARCHIVING:-true}
UPGRADE_PACKAGES=${UPGRADE_PACKAGES:-false}
TESLAUSB_HOSTNAME=${TESLAUSB_HOSTNAME:-troncam}
SAMBA_ENABLED=${SAMBA_ENABLED:-false}
SAMBA_GUEST=${SAMBA_GUEST:-false}
SNAPSHOTS_ENABLED=${SNAPSHOTS_ENABLED:-true}
INCREASE_ROOT_SIZE=${INCREASE_ROOT_SIZE:-0}
export camsize=${camsize:-90%}
export musicsize=${musicsize:-100%}
export usb_drive=${usb_drive:-''}

function setup_progress () {
  local setup_logfile=/boot/teslausb-headless-setup.log
  if [ $HEADLESS_SETUP = "true" ] && [ -w $setup_logfile ]
  then
    echo "$( date ) : $*" >> "$setup_logfile"
  fi
  echo "$@"
}

if [[ $EUID -ne 0 ]]
then
  setup_progress "STOP: Run sudo -i."
  exit 1
fi

function dehumanize () {
  echo $(($(echo "$1" | sed 's/GB/G/;s/MB/M/;s/KB/K/;s/G/*1024M/;s/M/*1024K/;s/K/*1024/')))
}

REBOOT=false

# wpa_supplicant should have a country code. Use US as the default
# to avoid using the disallowed channels in the US.
WPA=/etc/wpa_supplicant/wpa_supplicant.conf 
if ! grep -q "country=" $WPA
then
  setup_progress "adding country code to wpa_supplicant.conf"
  echo "country=US" >> $WPA
  REBOOT=true
fi

INCREASE_ROOT_SIZE=$(($(dehumanize "$INCREASE_ROOT_SIZE") / 512))

if [ "$INCREASE_ROOT_SIZE" != "0" ] && [ ! -e /dev/mmcblkp03 ]
then
  if [ ! -e /root/TESLAUSB_ROOT_PARTITION_INCREASED ]
  then
    touch /root/TESLAUSB_ROOT_PARTITION_INCREASED
    ROOTSTART=$(partx --show -g -o START /dev/mmcblk0p2)
    ROOTSIZE=$(partx --show -g -o SECTORS /dev/mmcblk0p2)
    ROOTSIZE=$((ROOTSIZE + INCREASE_ROOT_SIZE))
    echo "$ROOTSTART,$ROOTSIZE" | sfdisk --force /dev/mmcblk0 -N 2
    setup_progress "increased root partition size"
    REBOOT=true
  else
    setup_progress "increasing root filesystem size to match partition size"
    resize2fs /dev/mmcblk0p2
  fi
fi

if [ "$REBOOT" = "true" ]
then
  if [ -t 0 ]
  then
    setup_progress "please reboot for changes to take effect"
    exit
  else
    setup_progress "rebooting for changes to take effect"
    reboot
    exit
  fi
fi

function headless_setup_populate_variables () {
  # Pull in the conf file variables to make avail to this script and subscripts
  # If setup-teslausb is run from rc.local, the conf file will have been moved
  # to /root by rc.local
  if [ $HEADLESS_SETUP = "true" ]
  then
    if [ -e /boot/teslausb_setup_variables.conf ]
    then
      setup_progress "reading config from /boot/teslausb_setup_variables.conf"
      source /boot/teslausb_setup_variables.conf
    elif [ -e /root/teslausb_setup_variables.conf ]
    then
      setup_progress "reading config from /root/teslausb_setup_variables.conf"
      source /root/teslausb_setup_variables.conf
    else
      setup_progress "couldn't find config file"
    fi
  fi
}

function headless_setup_mark_setup_success () {
  if [ $HEADLESS_SETUP = "true" ]
  then
    rm -f /boot/TESLAUSB_SETUP_FAILED
    rm -f /boot/TESLAUSB_SETUP_STARTED
    touch /boot/TESLAUSB_SETUP_FINISHED
  fi
}

function isPi4 {
  grep -q "Pi 4" /sys/firmware/devicetree/base/model
}

function flash () {
  local ON=0
  local OFF=1
  if isPi4
  then
    ON=1
    OFF=0
  fi
  echo none > /sys/class/leds/led0/trigger
  echo $OFF > /sys/class/leds/led0/brightness
  sleep 1
  for ((i=1; i<=$1; i++))
  do
    echo $ON > /sys/class/leds/led0/brightness
    sleep .2
    echo $OFF > /sys/class/leds/led0/brightness
    sleep .8
  done
}

function headless_setup_progress_flash () {
  if [ $USE_LED_FOR_SETUP_PROGRESS = "true" ] && [ $HEADLESS_SETUP = "true" ] && [ ! -t 0 ]
  then
    flash "$1"
  fi
}

function verify_configuration () {
  /root/bin/verify-configuration.sh
}

function curlwrapper () {
  setup_progress "curl $*"
  while ! curl --fail "$@"
  do
    setup_progress "'curl $*' failed, retrying" > /dev/null
    sleep 3
  done
}

function fix_cmdline_txt_modules_load ()
{
  setup_progress "Fixing the modules-load parameter in /boot/cmdline.txt..."
  cp /boot/cmdline.txt ~
  sed 's/ modules-load=dwc2,g_ether/ modules-load=dwc2/' ~/cmdline.txt > /boot/cmdline.txt
  rm ~/cmdline.txt
  setup_progress "Fixed cmdline.txt."
}

BACKINGFILES_MOUNTPOINT=/backingfiles
MUTABLE_MOUNTPOINT=/mutable

function create_usb_drive_backing_files () {
  if [ ! -e "$BACKINGFILES_MOUNTPOINT" ]
  then
    mkdir "$BACKINGFILES_MOUNTPOINT"
  fi

  if [ ! -e "$MUTABLE_MOUNTPOINT" ]
  then
    mkdir "$MUTABLE_MOUNTPOINT"
  fi

  /root/bin/create-backingfiles-partition.sh "$BACKINGFILES_MOUNTPOINT" "$MUTABLE_MOUNTPOINT"

  if ! findmnt --mountpoint $BACKINGFILES_MOUNTPOINT
  then
    setup_progress "Mounting the partition for the backing files..."
    mount $BACKINGFILES_MOUNTPOINT
    setup_progress "Mounted the partition for the backing files."
  fi

  if [ ! -e $BACKINGFILES_MOUNTPOINT/cam_disk.bin ]
  then
    setup_progress "Creating backing disk files."
    /root/bin/create-backingfiles.sh "$camsize" "$musicsize" "$BACKINGFILES_MOUNTPOINT"
  else
    # mount cam image and make sure the right directories exist
    if modprobe -r g_mass_storage && mount /mnt/cam
    then
      mkdir -p /mnt/cam/TeslaCam
      mkdir -p /mnt/cam/TeslaTrackMode
      umount /mnt/cam
    else
      log "STOP: Couldn't check image"
      exit 1
    fi
  fi
}

function make_root_fs_readonly () {
  /root/bin/make-root-fs-readonly.sh
}

function update_package_index () {
  setup_progress "Updating package index files..."
  while ! apt-get update
  do
    setup_progress "Failed, retrying"
    sleep 2
  done
}

function upgrade_packages () {
  if [ "$UPGRADE_PACKAGES" = true ]
  then
    setup_progress "Upgrading installed packages..."
    apt-get --assume-yes upgrade
  else
    setup_progress "Skipping package upgrade."
  fi
}

function set_timezone () {
  # shellcheck disable=SC2154
  if [ -n "${timezone:+x}" ]
  then
    if [ -f "/usr/share/zoneinfo/$timezone" ]
    then
      ln -sf "/usr/share/zoneinfo/$timezone" /etc/localtime
    else
      setup_progress "invalid timezone: $timezone"
    fi
  fi
}

function cmd_diagnose {
  local hardware
  local os

  hardware=$( tr -d '\000' < /sys/firmware/devicetree/base/model )
  os=$(. /etc/os-release && echo "$PRETTY_NAME")
  {
    echo -e "====== summary ======"
    echo -e "hardware: ${hardware}"
    echo -e "OS: ${os}"
    if [ -e /root/teslausb_setup_variables.conf ]
    then
      echo "headless setup config in /root"
      source /root/teslausb_setup_variables.conf
    elif [ -e /boot/teslausb_setup_variables.conf ]
    then
      echo "headless setup config in /boot"
      source /boot/teslausb_setup_variables.conf
    else
      echo "headless setup config not found"
    fi
    if [ "${ARCHIVE_SYSTEM:-none}" = "cifs" ]
    then
      if grep -q '/mnt/archive' /etc/fstab
      then
        echo "CIFS archiving selected"
      else
        echo "CIFS archiving selected, but archive not defined in fstab"
      fi
    else
      echo "archive method: ${ARCHIVE_SYSTEM:-none}"
    fi

    if ! blkid -L backingfiles > /dev/null
    then
      echo "backingfiles partition does not exist"
    fi
    if [ ! -d /backingfiles ]
    then
      echo "backingfiles directory does not exist"
    fi
    if ! grep -q '/backingfiles' /etc/fstab
    then
      echo "backingfiles not in fstab"
    fi

    if [ ! -f /backingfiles/cam_disk.bin ]
    then
      echo "cam disk image does not exist"
    fi
    if ! grep -q '/backingfiles/cam_disk.bin' /etc/fstab
    then
      echo "cam disk image not in fstab"
    fi
    for LUN0 in /sys/devices/platform/soc/??980000.usb/gadget/lun0/file
    do
      if [ -e "$LUN0" ]
      then
        echo "lun0 connected, from file $(cat "$LUN0")"
      fi
    done
    for LUN1 in /sys/devices/platform/soc/??980000.usb/gadget/lun1/file
    do
      if [ -e "$LUN1" ]
      then
        echo "lun1 connected, from file $(cat "$LUN1")"
      fi
    done
    if ! blkid -L mutable > /dev/null
    then
      echo "mutable partition does not exist"
    fi
    if [ ! -d /mutable ]
    then
      echo "mutable directory does not exist"
    fi
    if ! grep -q '/mutable' /etc/fstab
    then
      echo "mutable not in fstab"
    fi

    numsnapshots=$( mount | grep -c snapshot )
    echo "$numsnapshots snapshots mounted"

    if [ ! -e /boot/TESLAUSB_SETUP_FINISHED ]
    then
      echo 'setup did not finish'
    fi

    echo -e "====== disk / images ======"
    parted -s /dev/mmcblk0 print || true
    if [ -n "${usb_drive:+x}" ]
    then
      parted -s "$usb_drive" print || true
    fi
    if [ -f /backingfiles/cam_disk.bin ]
    then
      echo "cam disk image has $(filefrag /backingfiles/cam_disk.bin | awk '{print $2}') extents"
      parted -s /backingfiles/cam_disk.bin print || true
    else
      echo "no cam disk image found"
    fi
    if [ -f /backingfiles/music_disk.bin ]
    then
      echo "music disk image has $(filefrag /backingfiles/music_disk.bin | awk '{print $2}') extents"
      parted -s /backingfiles/music_disk.bin print || true
    else
      echo "no music disk image found"
    fi

    echo -e "====== network ======"
    ifconfig
    iwconfig wlan0 | grep Link

    echo -e "====== fstab ======"
    if [ -e /etc/fstab ]
    then
      cat /etc/fstab
    else
      echo "no fstab found"
    fi

    echo -e "====== initial setup boot log ======"
    mkdir /tmp/root$$
    mount --bind / /tmp/root$$
    if [ -e /tmp/root$$/var/log/boot.log ]
    then
      cat /tmp/root$$/var/log/boot.log
    else
      echo "no boot log found"
    fi
    umount /tmp/root$$
    rmdir /tmp/root$$

    echo -e "====== setup log ======"
    if [ -e /boot/teslausb-headless-setup.log ]
    then
      cat /boot/teslausb-headless-setup.log
    else
      echo "no setup log found"
    fi

    echo -e "====== archiveloop log ======"
    if [ -e /mutable/archiveloop.log ]
    then
      cat /mutable/archiveloop.log
    else
      echo "no archiveloop log found"
    fi

    echo -e "====== system log ======"
    if [ -x /bin/logread ]
    then
      /bin/logread
    else
      echo "logread not installed"
    fi

    echo -e "====== dmesg ======"
    dmesg -T
    echo -e "====== process list and uptime ======"
    ps -eaf
    echo "$(hostname) has been $(uptime -p). System time is $(date)"
    echo -e "====== end of diagnostics ======"
  } |
    # clean up the output a bit
    tr '\r' '\n' |
    sed '/^ *$/d' |
    grep -a -v '^Reading package lists' |
    grep -a -v '^(Reading database' |
    grep -a -v "^Adding 'diversion of" |
    grep -a -v "^Removing 'diversion of" |
    sed -E 's/\o033\[0;32m//' |
    sed -E 's/\o033\[0m//'
}

export -f setup_progress
export HEADLESS_SETUP

headless_setup_populate_variables

INSTALL_DIR=${INSTALL_DIR:-/root/bin}
if [ "$INSTALL_DIR" != "/root/bin" ]
then
  setup_progress "WARNING: 'INSTALL_DIR' setup variable no longer supported"
fi

BRANCHNAME="$BRANCH"

if [ -n "${1:+x}" ]
then
  command=cmd_$1
  if typeset -f "$command" > /dev/null
  then
    shift
    $command "$@"
    exit 0
  else
    setup_progress "unknown command: $1"
    exit 1
  fi
fi

# Update /boot/config.txt if needed
if ! grep -q 'dtoverlay=dwc2' /boot/config.txt
then
  echo -e "dtoverlay=dwc2\n" >> /boot/config.txt
fi

# update_package_index

# set time zone so we get decent timestamps in the rest of the setup log
set_timezone

# Flash for stage 2 headless (verify requested configuration)
headless_setup_progress_flash 2

setup_progress "Verifying that the requested configuration is valid..."

verify_configuration

# Flash for Stage 3 headless (grab scripts)
headless_setup_progress_flash 3

pushd ~

fix_cmdline_txt_modules_load

# Flash for stage 4 headless (Create backing files)
headless_setup_progress_flash 4

create_usb_drive_backing_files

if [ "$CONFIGURE_ARCHIVING" = true ]
then
  setup_progress "calling configure.sh"
  export -f curlwrapper
  /root/bin/configure.sh
else
  setup_progress "skipping configure.sh"
fi

if [ "$SAMBA_ENABLED" = "true" ] 
then
  if [ "$SNAPSHOTS_ENABLED" = "true" ]
  then
    export SAMBA_GUEST
    /root/bin/configure-samba.sh
  else
    setup_progress "snapshots disabled, skipping Samba configuration"
  fi
fi

if [ ! -L /var/lib/dhcp ]
then
  if ! findmnt --mountpoint /mutable
  then
    mount /mutable
  fi
  mkdir -p /mutable/varlib
  mv /var/lib/dhcp /mutable/varlib
  ln -s /mutable/varlib/dhcp /var/lib/dhcp
fi

mkdir -p /mutable/pm2
export PM2_HOME=/mutable/pm2

if [ ! -d /mutable/pm2/modules/pm2-logrotate ]
then
  cp -r /root/src/pm2-logrotate /mutable/pm2/
  pm2 install file:///mutable/pm2/pm2-logrotate
  pm2 update
fi

systemctl stop wpa_supplicant.service
systemctl disable wpa_supplicant.service

make_root_fs_readonly

# upgrade_packages

headless_setup_mark_setup_success

# Flash for stage 5 headless (Mark success, FS readonly)
headless_setup_progress_flash 5

setup_progress "All done."

if [ -t 0 ]
then
  setup_progress '(reboot now for changes to take effect)'
fi

# reboot for good measure, also restarts the rc.local script
reboot